name: Update Schedule Data from Google Sheet

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

# --- NEW: Grant write permissions to the job ---
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code
      - name: Check out repo
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install Python dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script to generate the JSON file
      - name: Run script to convert Google Sheet to JSON
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python convert_excel.py

      # Step 5: Commit the new JSON file back to the repository
      - name: Commit and push if there are changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add S26schedule.json
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Automated schedule data update"
            git push
          else
            echo "No changes to commit."
          fi
